"""
Enumerations for the Social Fabric Matrix (SFM) framework.

.. deprecated::
    The enum definitions have been moved to the ``models.enums`` package, which
    is split into domain-scoped modules for easier navigation and maintenance.
    This module is kept as a **compatibility shim**: all names are re-exported
    here so that existing code using::

        from models.sfm_enums import ValueCategory, RelationshipKind, …

    continues to work without modification.

    Prefer importing directly from ``models.enums`` or the relevant sub-module
    (e.g. ``models.enums.values``) in new code.
"""

# Re-export every public name from the new domain-scoped package so that
# ``from models.sfm_enums import X`` keeps working for all downstream code.
from models.enums import (  # noqa: F401  (re-exported for backward compat)
    # values
    ValueCategory,
    SocialValueDimension,
    ValueSystemType,
    ValueJudgmentType,
    CeremonialInstrumentalType,
    # institutions
    InstitutionLayer,
    PathDependencyType,
    InstitutionalChangeType,
    LegitimacySource,
    InstitutionalScope,
    GovernanceMechanism,
    EnforcementType,
    InstitutionalLevel,
    NormativeFramework,
    DeontologicalCategory,
    CommonsGovernanceType,
    TransactionCostType,
    CoordinationMechanismType,
    CoordinationScope,
    AdjustmentType,
    AdjustmentTrigger,
    BoundaryType,
    SystemBoundaryType,
    # resources
    ResourceType,
    FlowNature,
    FlowType,
    ProvisioningStage,
    DeliveryQuantificationMethod,
    # relationships
    RelationshipKind,
    CrossImpactType,
    ConflictType,
    ConflictResolutionMethod,
    # policies
    PolicyInstrumentType,
    PolicyType,
    PolicyScope,
    ImplementationComplexity,
    PolicyEffectiveness,
    EvaluationMethod,
    # systems
    ChangeType,
    BehaviorPatternType,
    FeedbackPolarity,
    FeedbackType,
    TemporalFunctionType,
    SystemPropertyType,
    SystemArchetype,
    SystemLevel,
    EvolutionaryStage,
    DependencyStrength,
    SequenceStage,
    ProblemSolvingStage,
    # analysis
    ValidationRuleType,
    CorrelationType,
    EvidenceQuality,
    CriteriaType,
    MeasurementApproach,
    CorrelationScale,
    CriteriaPriority,
    StatisticalMethod,
    MatrixOperationType,
    MatrixConstructionStage,
    DigraphAnalysisType,
    NetworkMetricType,
    DigraphNodeType,
    AnalyticalMethod,
    ValidationMethod,
    IndicatorType,
    # technology
    ToolSkillTechnologyType,
    TechnologyReadinessLevel,
    TechnologyMaturityLevel,
    SkillLevel,
    KnowledgeType,
    LearningMethod,
    InformationSystem,
    # stakeholders
    PowerResourceType,
    StakeholderType,
    ParticipationLevel,
    DecisionMakingApproach,
    DecisionMakingType,
    CommunicationChannel,
    # social
    SocialFabricIndicatorType,
    SocialCostType,
    # exceptions and utilities
    SFMEnumError,
    IncompatibleEnumError,
    InvalidEnumOperationError,
    EnumValidator,
    validate_enum_operation,
)

# Module metadata (preserved for backward compatibility)
__version__ = "1.0.0"
__author__ = "SFM Development Team"
__all__ = [
    # Core enums
    "ValueCategory",
    "InstitutionLayer",
    "ResourceType",
    "FlowNature",
    "FlowType",
    "PolicyInstrumentType",
    "ChangeType",
    "BehaviorPatternType",
    "FeedbackPolarity",
    "FeedbackType",
    "TemporalFunctionType",
    "ValidationRuleType",
    "SystemPropertyType",
    "RelationshipKind",
    "PowerResourceType",
    "ToolSkillTechnologyType",
    "PathDependencyType",
    "InstitutionalChangeType",
    "TechnologyReadinessLevel",
    "LegitimacySource",
    "CorrelationType",
    "EvidenceQuality",
    "CriteriaType",
    "MeasurementApproach",
    "CeremonialInstrumentalType",
    "ValueJudgmentType",
    "DigraphNodeType",
    "ProblemSolvingStage",
    "InstitutionalScope",
    "GovernanceMechanism",
    "CrossImpactType",
    "EnforcementType",
    "DecisionMakingType",
    "TransactionCostType",
    "CoordinationMechanismType",
    "CoordinationScope",
    "CommonsGovernanceType",
    "SocialValueDimension",
    "SystemArchetype",
    "ValueSystemType",
    "SocialFabricIndicatorType",
    "SocialCostType",
    "InstitutionalLevel",
    "NormativeFramework",
    "EvolutionaryStage",
    "DependencyStrength",
    "CriteriaPriority",
    "CorrelationScale",
    "BoundaryType",
    "ProvisioningStage",
    "ConflictType",
    "DigraphAnalysisType",
    "NetworkMetricType",
    "SequenceStage",
    "IndicatorType",
    "DeontologicalCategory",
    "StatisticalMethod",
    "AdjustmentType",
    "SystemBoundaryType",
    "DeliveryQuantificationMethod",
    "AdjustmentTrigger",
    "MatrixOperationType",
    "SystemLevel",
    "PolicyType",
    "PolicyScope",
    "ImplementationComplexity",
    "PolicyEffectiveness",
    "EvaluationMethod",
    "TechnologyMaturityLevel",
    "SkillLevel",
    "KnowledgeType",
    "ValidationMethod",
    "AnalyticalMethod",
    "MatrixConstructionStage",
    "StakeholderType",
    "ParticipationLevel",
    "DecisionMakingApproach",
    "ConflictResolutionMethod",
    "CommunicationChannel",
    "LearningMethod",
    "InformationSystem",
    # Exception classes
    "SFMEnumError",
    "IncompatibleEnumError",
    "InvalidEnumOperationError",
    # Validation utilities
    "EnumValidator",
    "validate_enum_operation",
]
